# permissions for end users to edit monitorpushes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitorpush-editor-role
rules:
- apiGroups:
  - kubemonitor.kubemonitor
  resources:
  - monitorpushes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubemonitor.kubemonitor
  resources:
  - monitorpushes/status
  verbs:
  - get
