# permissions for end users to view monitorpushes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitorpush-viewer-role
rules:
- apiGroups:
  - kubemonitor.kubemonitor
  resources:
  - monitorpushes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubemonitor.kubemonitor
  resources:
  - monitorpushes/status
  verbs:
  - get
