# permissions for end users to view redismonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: redismonitor-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubemonitor
    app.kubernetes.io/part-of: kubemonitor
    app.kubernetes.io/managed-by: kustomize
  name: redismonitor-viewer-role
rules:
- apiGroups:
  - kubemonitor.io.kubemonitor.io
  resources:
  - redismonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubemonitor.io.kubemonitor.io
  resources:
  - redismonitors/status
  verbs:
  - get
