# permissions for end users to edit redismonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: redismonitor-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubemonitor
    app.kubernetes.io/part-of: kubemonitor
    app.kubernetes.io/managed-by: kustomize
  name: redismonitor-editor-role
rules:
- apiGroups:
  - kubemonitor.io.kubemonitor.io
  resources:
  - redismonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubemonitor.io.kubemonitor.io
  resources:
  - redismonitors/status
  verbs:
  - get
