---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kubemonitor.io.kubemonitor.io
  resources:
  - mysqlmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubemonitor.io.kubemonitor.io
  resources:
  - mysqlmonitors/finalizers
  verbs:
  - update
- apiGroups:
  - kubemonitor.io.kubemonitor.io
  resources:
  - mysqlmonitors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubemonitor.io.kubemonitor.io
  resources:
  - prometheuspushes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubemonitor.io.kubemonitor.io
  resources:
  - prometheuspushes/finalizers
  verbs:
  - update
- apiGroups:
  - kubemonitor.io.kubemonitor.io
  resources:
  - prometheuspushes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubemonitor.io.kubemonitor.io
  resources:
  - redismonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubemonitor.io.kubemonitor.io
  resources:
  - redismonitors/finalizers
  verbs:
  - update
- apiGroups:
  - kubemonitor.io.kubemonitor.io
  resources:
  - redismonitors/status
  verbs:
  - get
  - patch
  - update
