---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kubemonitor.kubemonitor
  resources:
  - monitorpushes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubemonitor.kubemonitor
  resources:
  - monitorpushes/finalizers
  verbs:
  - update
- apiGroups:
  - kubemonitor.kubemonitor
  resources:
  - monitorpushes/status
  verbs:
  - get
  - patch
  - update
