apiVersion: kubemonitor.io.kubemonitor.io/v1
kind: PrometheusPush
metadata:
  name: prometheuspush
spec:
  url: "http://192.168.11.207:9090/api/v1/write"
  timeout: 5000
  dial_timeout: 2500
  max_idle_conns_per_host: 100

