apiVersion: kubemonitor.io.kubemonitor.io/v1
kind: Monitor
metadata:
  name: uc-redis1
spec:
  labels:
    name: redis
    namespace: uc
  period: "25s"
  model:
    name: "redis"
    config:
      address: "redis.uc"
      port: "6379"
      pool_size: "10"